apiVersion: apps/v1
kind: Deployment
metadata:
  name: workstation-audit-deployment
  namespace: workstation-audit
  labels:
    app: workstation-audit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workstation-audit
  template:
    metadata:
      labels:
        app: workstation-audit
    spec:
      containers:
        - name: workstation-audit
          image: xzxzxzxze/protected-workstation-audit-service:v1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
