apiVersion: apps/v1
kind: Deployment
metadata:
  name: pupils-bachelor-deployment
  namespace: pupils-bachelor
  labels:
    app: pupils-bachelor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pupils-bachelor
  template:
    metadata:
      labels:
        app: pupils-bachelor
    spec:
      containers:
        - name: pupils-bachelor
          image: xzxzxzxze/pupils-bachelor-openstack-service:v1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
