apiVersion: v1
kind: Service
metadata:
  name: workstation-audit-service
  namespace: workstation-audit
  labels:
    app: workstation-audit
spec:
  type: NodePort
  selector:
    app: workstation-audit
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
