apiVersion: v1
kind: Service
metadata:
  name: pupils-bachelor-service
  namespace: pupils-bachelor
  labels:
    app: pupils-bachelor
spec:
  type: NodePort
  selector:
    app: pupils-bachelor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
